from . import (
    TxCtrlCmd,
    C3SoftResetCmd,
    C3HardResetCmd,
    C3FactoryResetCmd,
    CoNodeEnableCmd,
    CoNodeStatusCmd,
    CoSdoWriteCmd,
    CoSyncCmd,
    OpdSysEnableCmd,
    OpdScanCmd,
    OpdProbeCmd,
    OpdEnableCmd,
    OpdResetCmd,
    OpdStatusCmd,
    RtcSetTimeCmd,
    TimeSyncCmd,
    BeaconPingCmd,
    PingCmd,
    RxTestCmd,
    CoSdoReadCmd,
)

edl_cmd_dict = {
    TxCtrlCmd.id: "TxCtrlCmd",
    C3SoftResetCmd.id: "C3SoftResetCmd",
    C3HardResetCmd.id: "C3HardResetCmd",
    C3FactoryResetCmd.id: "C3FactoryResetCmd",
    CoNodeEnableCmd.id: "CoNodeEnableCmd",
    CoNodeStatusCmd.id: "CoNodeStatusCmd",
    CoSdoWriteCmd.id: "CoSdoWriteCmd",
    CoSyncCmd.id: "CoSyncCmd",
    OpdSysEnableCmd.id: "OpdSysEnableCmd",
    OpdScanCmd.id: "OpdScanCmd",
    OpdProbeCmd.id: "OpdProbeCmd",
    OpdEnableCmd.id: "OpdEnableCmd",
    OpdResetCmd.id: "OpdResetCmd",
    OpdStatusCmd.id: "OpdStatusCmd",
    RtcSetTimeCmd.id: " RtcSetTimeCmd",
    TimeSyncCmd.id: "TimeSyncCmd",
    BeaconPingCmd.id: "BeaconPingCmd",
    PingCmd.id: "PingCmd",
    RxTestCmd.id: "RxTestCmd",
    CoSdoReadCmd.id: "CoSdoReadCmd",
}
