# DO NOT EDIT - THIS FILE IS AUTO GENERATED BY `scripts/code_gen/generate_fop_events.py`
from common.fsm import CopEvent


class FopEvent(CopEvent):
    E1 = 1
    E2 = 2
    E3 = 3
    E4 = 4
    E5 = 5
    E6_B = 6
    E7_B = 7
    E8_B = 8
    E9_B = 9
    E10_B = 10
    E11_B = 11
    E12_B = 12
    E13 = 13
    E14 = 14
    E15 = 15
    E16_B = 16
    E17_B = 17
    E18_B = 18
    E19 = 19
    E20 = 20
    E21_B = 21
    E22 = 22
    E23 = 23
    E24 = 24
    E25_B = 25
    E26 = 26
    E27_B = 27
    E28 = 28
    E29 = 29
    E30 = 30
    E31_B = 31
    E32_B = 32
    E33_B = 33
    E34_B = 34
    E35_B = 35
    E36 = 36
    E37 = 37
    E38 = 38
    E39 = 39
    E40 = 40
    E41 = 41
    E42 = 42
    E43 = 43
    E44 = 44
    E45 = 45
    E46 = 46
    E101 = 101
    E102 = 102
    E103 = 103
    E104 = 104
