name: oresat1
nice_name: OreSat1
id: 3
edl:
  spacecraft_id: 0x4F53  # aka "OS" in ASCII
beacon:
  revision: 0
  ax25:
    dest_callsign: SPACE
    dest_ssid: 0  # primary station
    src_callsign: KJ7SAT
    src_ssid: 11  # balloons, aircraft, spacecraft, etc
    control: 0x3  # ui-frame
    pid: 0xf0  # no L3 protocol
    command: false
    response: true
  fields:
    # c3
    - [status]
