name: oresat0_5
nice_name: OreSat0.5
id: 2
beacon:
  revision: 0
  ax25:
    dest_callsign: SPACE
    dest_ssid: 0  # primary station
    src_callsign: KJ7SAT
    src_ssid: 11  # balloons, aircraft, spacecraft, etc
    control: 0x3  # ui-frame
    pid: 0xf0  # no L3 protocol
    command: false
    response: true
  fields:
    # c3
    - [status]
    - [mode]
    - [system, uptime]
    - [system, unix_time]
    - [system, power_cycles]
    - [system, storage_percent]
    - [lband, rx_bytes]
    - [lband, rx_packets]
    - [lband, rssi]
    - [lband, synth_relock_count]
    - [uhf, rx_bytes]
    - [uhf, rx_packets]
    - [uhf, rssi]
    - [edl, sequence_count]
    - [edl, rejected_count]
    - [fread_cache, length]
    - [fwrite_cache, length]
    - [updater, cache_length]
    - [adcs_manager, mode]
    # battery_1
    - [battery_1, pack_1_vbatt]
    - [battery_1, pack_1_vcell]
    - [battery_1, pack_1_vcell_max]
    - [battery_1, pack_1_vcell_min]
    - [battery_1, pack_1_vcell_1]
    - [battery_1, pack_1_vcell_2]
    - [battery_1, pack_1_vcell_avg]
    - [battery_1, pack_1_temperature]
    - [battery_1, pack_1_temperature_avg]
    - [battery_1, pack_1_temperature_max]
    - [battery_1, pack_1_temperature_min]
    - [battery_1, pack_1_current]
    - [battery_1, pack_1_current_avg]
    - [battery_1, pack_1_current_max]
    - [battery_1, pack_1_current_min]
    - [battery_1, pack_1_status]
    - [battery_1, pack_1_reported_state_of_charge]
    - [battery_1, pack_1_full_capacity]
    - [battery_1, pack_1_reported_capacity]
    - [battery_1, pack_2_vbatt]
    - [battery_1, pack_2_vcell]
    - [battery_1, pack_2_vcell_max]
    - [battery_1, pack_2_vcell_min]
    - [battery_1, pack_2_vcell_1]
    - [battery_1, pack_2_vcell_2]
    - [battery_1, pack_2_vcell_avg]
    - [battery_1, pack_2_temperature]
    - [battery_1, pack_2_temperature_avg]
    - [battery_1, pack_2_temperature_max]
    - [battery_1, pack_2_temperature_min]
    - [battery_1, pack_2_current]
    - [battery_1, pack_2_current_avg]
    - [battery_1, pack_2_current_max]
    - [battery_1, pack_2_current_min]
    - [battery_1, pack_2_status]
    - [battery_1, pack_2_reported_state_of_charge]
    - [battery_1, pack_2_full_capacity]
    - [battery_1, pack_2_reported_capacity]
    # solar_1
    - [solar_1, output_voltage_avg]
    - [solar_1, output_current_avg]
    - [solar_1, output_power_avg]
    - [solar_1, output_voltage_max]
    - [solar_1, output_current_max]
    - [solar_1, output_power_max]
    - [solar_1, output_energy]
    # solar_2
    - [solar_2, output_voltage_avg]
    - [solar_2, output_current_avg]
    - [solar_2, output_power_avg]
    - [solar_2, output_voltage_max]
    - [solar_2, output_current_max]
    - [solar_2, output_power_max]
    - [solar_2, output_energy]
    # solar_3
    - [solar_3, output_voltage_avg]
    - [solar_3, output_current_avg]
    - [solar_3, output_power_avg]
    - [solar_3, output_voltage_max]
    - [solar_3, output_current_max]
    - [solar_3, output_power_max]
    - [solar_3, output_energy]
    # solar_4
    - [solar_4, output_voltage_avg]
    - [solar_4, output_current_avg]
    - [solar_4, output_power_avg]
    - [solar_4, output_voltage_max]
    - [solar_4, output_current_max]
    - [solar_4, output_power_max]
    - [solar_4, output_energy]
    # solar_5
    - [solar_5, output_voltage_avg]
    - [solar_5, output_current_avg]
    - [solar_5, output_power_avg]
    - [solar_5, output_voltage_max]
    - [solar_5, output_current_max]
    - [solar_5, output_power_max]
    - [solar_5, output_energy]
    # solar_6
    - [solar_6, output_voltage_avg]
    - [solar_6, output_current_avg]
    - [solar_6, output_power_avg]
    - [solar_6, output_voltage_max]
    - [solar_6, output_current_max]
    - [solar_6, output_power_max]
    - [solar_6, output_energy]
    # star_tracker_1
    - [star_tracker_1, system_storage_percent]
    - [star_tracker_1, status]
    # gps
    - [gps, system_storage_percent]
    - [gps, status]
    - [gps, skytraq_number_of_sv]
    - [gps, skytraq_fix_mode]
    # adcs
    - [adcs, gyroscope_roll_rate]
    - [adcs, gyroscope_pitch_rate]
    - [adcs, gyroscope_yaw_rate]
    # dxwifi
    - [dxwifi, system_storage_percent]
    - [dxwifi, status]
    - [dxwifi, radio_temperature]
    # cfc_processor
    - [cfc_processor, system_storage_percent]
    - [cfc_processor, camera_status]
    - [cfc_processor, camera_temperature]
    - [cfc_processor, tec_status]
