name: oresat0
nice_name: OreSat0
id: 1
edl:
  spacecraft_id: 0x4F53  # aka "OS" in ASCII
beacon:
  revision: 0
  ax25:
    dest_callsign: SPACE
    dest_ssid: 0
    src_callsign: KJ7SAT
    src_ssid: 0
    control: 0x3  # ui-frame
    pid: 0xf0  # no L3 protocol
    command: false
    response: false
  fields:
    # c3
    - [status]
    - [system, uptime]
    - [system, unix_time]
    - [system, power_cycles]
    - [system, storage_percent]
    - [lband, rx_bytes]
    - [lband, rx_packets]
    - [lband, rssi]
    - [uhf, rx_bytes]
    - [uhf, rx_packets]
    - [uhf, rssi]
    - [system, boot_select]
    - [edl, sequence_count]
    - [edl, rejected_count]
    # battery_1
    - [battery_1, pack_1_vbatt]
    - [battery_1, pack_1_vcell]
    - [battery_1, pack_1_vcell_max]
    - [battery_1, pack_1_vcell_min]
    - [battery_1, pack_1_vcell_1]
    - [battery_1, pack_1_vcell_2]
    - [battery_1, pack_1_vcell_avg]
    - [battery_1, pack_1_temperature]
    - [padding_byte]
    - [battery_1, pack_1_temperature_avg]
    - [padding_byte]
    - [battery_1, pack_1_temperature_max]
    - [padding_byte]
    - [battery_1, pack_1_temperature_min]
    - [padding_byte]
    - [battery_1, pack_1_current]
    - [battery_1, pack_1_current_avg]
    - [battery_1, pack_1_current_max]
    - [battery_1, pack_1_current_min]
    - [battery_1, pack_1_status]
    - [battery_1, pack_1_reported_state_of_charge]
    - [battery_1, pack_1_full_capacity]
    - [battery_1, pack_1_reported_capacity]
    - [battery_1, pack_2_vbatt]
    - [battery_1, pack_2_vcell]
    - [battery_1, pack_2_vcell_max]
    - [battery_1, pack_2_vcell_min]
    - [battery_1, pack_2_vcell_1]
    - [battery_1, pack_2_vcell_2]
    - [battery_1, pack_2_vcell_avg]
    - [battery_1, pack_2_temperature]
    - [padding_byte]
    - [battery_1, pack_2_temperature_avg]
    - [padding_byte]
    - [battery_1, pack_2_temperature_max]
    - [padding_byte]
    - [battery_1, pack_2_temperature_min]
    - [padding_byte]
    - [battery_1, pack_2_current]
    - [battery_1, pack_2_current_avg]
    - [battery_1, pack_2_current_max]
    - [battery_1, pack_2_current_min]
    - [battery_1, pack_2_status]
    - [battery_1, pack_2_reported_state_of_charge]
    - [battery_1, pack_2_full_capacity]
    - [battery_1, pack_2_reported_capacity]
    # solar_1
    - [solar_1, output_voltage_avg]
    - [solar_1, output_current_avg]
    - [solar_1, output_power_avg]
    - [solar_1, output_voltage_max]
    - [solar_1, output_current_max]
    - [solar_1, output_power_max]
    - [solar_1, output_energy]
    # solar_2
    - [solar_2, output_voltage_avg]
    - [solar_2, output_current_avg]
    - [solar_2, output_power_avg]
    - [solar_2, output_voltage_max]
    - [solar_2, output_current_max]
    - [solar_2, output_power_max]
    - [solar_2, output_energy]
    # solar_3
    - [solar_3, output_voltage_avg]
    - [solar_3, output_current_avg]
    - [solar_3, output_power_avg]
    - [solar_3, output_voltage_max]
    - [solar_3, output_current_max]
    - [solar_3, output_power_max]
    - [solar_3, output_energy]
    # solar_4
    - [solar_4, output_voltage_avg]
    - [solar_4, output_current_avg]
    - [solar_4, output_power_avg]
    - [solar_4, output_voltage_max]
    - [solar_4, output_current_max]
    - [solar_4, output_power_max]
    - [solar_4, output_energy]
    # star_tracker_1
    - [star_tracker_1, system_storage_percent]
    - [star_tracker_1, fread_cache_length]
    - [star_tracker_1, updater_status]
    - [star_tracker_1, updater_cache_length]
    - [star_tracker_1, orientation_right_ascension]
    - [star_tracker_1, orientation_declination]
    - [star_tracker_1, orientation_roll]
    - [star_tracker_1, orientation_time_since_midnight]
    # gps
    - [gps, system_storage_percent]
    - [gps, fread_cache_length]
    - [gps, updater_status]
    - [gps, updater_cache_length]
    - [gps, status]
    - [gps, skytraq_number_of_sv]
    - [gps, skytraq_ecef_x]
    - [gps, skytraq_ecef_y]
    - [gps, skytraq_ecef_z]
    - [gps, skytraq_ecef_vx]
    - [gps, skytraq_ecef_vy]
    - [gps, skytraq_ecef_vz]
    - [gps, skytraq_time_since_midnight]
    # adcs
    - [adcs, gyroscope_roll_rate]
    - [adcs, gyroscope_pitch_rate]
    - [adcs, gyroscope_yaw_rate]
    - [adcs, temperature]
    # dxwifi
    - [dxwifi, system_storage_percent]
    - [dxwifi, fread_cache_length]
    - [dxwifi, updater_status]
    - [dxwifi, updater_cache_length]
    - [dxwifi, status]
